/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "Cleaner 知识库",
  "description": "Cleaner 知识库",
  "base": "/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/favicon.ico"
      }
    ],
    [
      "meta",
      {
        "name": "viewport",
        "content": "width=device-width,initial-scale=1,user-scalable=no"
      }
    ]
  ],
  "pages": [
    {
      "title": "首页",
      "frontmatter": {
        "home": true,
        "title": "首页",
        "author": "Cleaner",
        "heroText": null,
        "tagline": "“岁月漫长，要心地善良”",
        "heroImage": "/logo.jpg",
        "heroImageStyle": {
          "maxWidth": "500px",
          "display": "block",
          "margin": "-12rem auto 1.5rem",
          "boxShadow": "0 5px 18px rgba(0,0,0,0.2)"
        },
        "readingShow": false
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-9280c340",
      "path": "/",
      "lastUpdated": "2023/11/21 下午7:40:44",
      "lastUpdatedTimestamp": 1700566844000
    },
    {
      "title": "使用 Docker Compose 部署 Elasticsearch + Kibana",
      "frontmatter": {
        "title": "使用 Docker Compose 部署 Elasticsearch + Kibana",
        "date": "2023-06-06T00:00:00.000Z",
        "author": "Cleaner",
        "categories": [
          "后端"
        ],
        "tags": [
          "Docker"
        ],
        "readingShow": "top"
      },
      "regularPath": "/backend/docker/Elasticsearch.html",
      "relativePath": "backend/docker/Elasticsearch.md",
      "key": "v-f6dcfe16",
      "path": "/backend/docker/Elasticsearch.html",
      "headers": [
        {
          "level": 2,
          "title": "服务器目录结构",
          "slug": "服务器目录结构"
        },
        {
          "level": 2,
          "title": "部署 Elasticsearch 和 Kibana",
          "slug": "部署-elasticsearch-和-kibana"
        },
        {
          "level": 3,
          "title": "启动容器",
          "slug": "启动容器"
        },
        {
          "level": 3,
          "title": "设置登陆密码",
          "slug": "设置登陆密码"
        },
        {
          "level": 3,
          "title": "完整配置文件内容",
          "slug": "完整配置文件内容"
        },
        {
          "level": 2,
          "title": "Spring Boot 整合 Elasticsearch",
          "slug": "spring-boot-整合-elasticsearch"
        },
        {
          "level": 3,
          "title": "添加依赖",
          "slug": "添加依赖"
        },
        {
          "level": 3,
          "title": "添加配置",
          "slug": "添加配置"
        },
        {
          "level": 3,
          "title": "使用",
          "slug": "使用"
        },
        {
          "level": 2,
          "title": "问题",
          "slug": "问题"
        }
      ],
      "lastUpdated": "2023/12/20 下午3:12:16",
      "lastUpdatedTimestamp": 1703056336000
    },
    {
      "title": "使用 Dockerfile + Docker Compose 部署 Web 项目",
      "frontmatter": {
        "title": "使用 Dockerfile + Docker Compose 部署 Web 项目",
        "date": "2023-06-06T00:00:00.000Z",
        "author": "Cleaner",
        "categories": [
          "后端"
        ],
        "tags": [
          "Docker"
        ],
        "readingShow": "top"
      },
      "regularPath": "/backend/docker/Web.html",
      "relativePath": "backend/docker/Web.md",
      "key": "v-65a62e07",
      "path": "/backend/docker/Web.html",
      "headers": [
        {
          "level": 2,
          "title": "服务器目录结构",
          "slug": "服务器目录结构"
        },
        {
          "level": 2,
          "title": "数据库",
          "slug": "数据库"
        },
        {
          "level": 3,
          "title": "拉取 MySQL 镜像",
          "slug": "拉取-mysql-镜像"
        },
        {
          "level": 3,
          "title": "启动 MySQL 容器",
          "slug": "启动-mysql-容器"
        },
        {
          "level": 2,
          "title": "制作 JDK17 镜像",
          "slug": "制作-jdk17-镜像"
        },
        {
          "level": 3,
          "title": "下载 JDK",
          "slug": "下载-jdk"
        },
        {
          "level": 3,
          "title": "编写 Dockerfile 文件",
          "slug": "编写-dockerfile-文件"
        },
        {
          "level": 3,
          "title": "构建 JDK 镜像",
          "slug": "构建-jdk-镜像"
        },
        {
          "level": 2,
          "title": "后端",
          "slug": "后端"
        },
        {
          "level": 3,
          "title": "编写 Dockerfile 文件",
          "slug": "编写-dockerfile-文件-2"
        },
        {
          "level": 3,
          "title": "启动容器",
          "slug": "启动容器"
        },
        {
          "level": 2,
          "title": "前端",
          "slug": "前端"
        },
        {
          "level": 3,
          "title": "项目打包",
          "slug": "项目打包"
        },
        {
          "level": 3,
          "title": "编写 nginx.conf 配置文件",
          "slug": "编写-nginx-conf-配置文件"
        },
        {
          "level": 3,
          "title": "编写 Dockerfile 文件",
          "slug": "编写-dockerfile-文件-3"
        },
        {
          "level": 3,
          "title": "启动容器",
          "slug": "启动容器-2"
        },
        {
          "level": 2,
          "title": "问题",
          "slug": "问题"
        }
      ],
      "lastUpdated": "2023/12/20 下午3:12:16",
      "lastUpdatedTimestamp": 1703056336000
    },
    {
      "title": "微服务架构中实施应用开发的十二要素",
      "frontmatter": {
        "title": "微服务架构中实施应用开发的十二要素",
        "date": "2023-07-24T00:00:00.000Z",
        "author": "Cleaner",
        "categories": [
          "后端"
        ],
        "tags": [
          "Micorservice"
        ],
        "readingShow": "top"
      },
      "regularPath": "/backend/microservice/twelve-factor.html",
      "relativePath": "backend/microservice/twelve-factor.md",
      "key": "v-1227ff87",
      "path": "/backend/microservice/twelve-factor.html",
      "headers": [
        {
          "level": 2,
          "title": "十二要素",
          "slug": "十二要素"
        },
        {
          "level": 3,
          "title": "基准代码",
          "slug": "基准代码"
        },
        {
          "level": 3,
          "title": "依赖",
          "slug": "依赖"
        },
        {
          "level": 3,
          "title": "配置",
          "slug": "配置"
        },
        {
          "level": 3,
          "title": "支撑服务",
          "slug": "支撑服务"
        },
        {
          "level": 3,
          "title": "构建、发布、运行",
          "slug": "构建、发布、运行"
        },
        {
          "level": 3,
          "title": "进程&端口绑定&并发&易处理",
          "slug": "进程-端口绑定-并发-易处理"
        },
        {
          "level": 3,
          "title": "开发环境和线上环境等价",
          "slug": "开发环境和线上环境等价"
        },
        {
          "level": 3,
          "title": "日志",
          "slug": "日志"
        },
        {
          "level": 3,
          "title": "管理进程",
          "slug": "管理进程"
        },
        {
          "level": 2,
          "title": "更多",
          "slug": "更多"
        },
        {
          "level": 2,
          "title": "末尾",
          "slug": "末尾"
        }
      ],
      "lastUpdated": "2023/12/20 上午10:50:10",
      "lastUpdatedTimestamp": 1703040610000
    },
    {
      "title": "EasyExcel 导出多张图片",
      "frontmatter": {
        "title": "EasyExcel 导出多张图片",
        "date": "2024-04-09T00:00:00.000Z",
        "author": "Cleaner",
        "categories": [
          "后端"
        ],
        "tags": [
          "EasyExcel"
        ],
        "readingShow": "top"
      },
      "regularPath": "/backend/work/easyexcel.html",
      "relativePath": "backend/work/easyexcel.md",
      "key": "v-41e2b063",
      "path": "/backend/work/easyexcel.html",
      "headers": [
        {
          "level": 2,
          "title": "实现效果",
          "slug": "实现效果"
        },
        {
          "level": 2,
          "title": "实现过程",
          "slug": "实现过程"
        },
        {
          "level": 3,
          "title": "1、引入依赖",
          "slug": "_1、引入依赖"
        },
        {
          "level": 3,
          "title": "2、定义实体类",
          "slug": "_2、定义实体类"
        },
        {
          "level": 3,
          "title": "3、定义转换器",
          "slug": "_3、定义转换器"
        },
        {
          "level": 3,
          "title": "4、定义拦截器",
          "slug": "_4、定义拦截器"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        }
      ],
      "lastUpdated": "2024/4/9 下午6:43:22",
      "lastUpdatedTimestamp": 1712659402000
    },
    {
      "title": "SQL 语句执行计划分析",
      "frontmatter": {
        "title": "SQL 语句执行计划分析",
        "date": "2023-08-23T00:00:00.000Z",
        "author": "Cleaner",
        "categories": [
          "后端"
        ],
        "tags": [
          "MySQL"
        ],
        "readingShow": "top"
      },
      "regularPath": "/backend/mysql/explain.html",
      "relativePath": "backend/mysql/explain.md",
      "key": "v-15ca2d81",
      "path": "/backend/mysql/explain.html",
      "headers": [
        {
          "level": 2,
          "title": "前言",
          "slug": "前言"
        },
        {
          "level": 2,
          "title": "Explain 各字段含义",
          "slug": "explain-各字段含义"
        },
        {
          "level": 3,
          "title": "id",
          "slug": "id"
        },
        {
          "level": 3,
          "title": "select_type",
          "slug": "select-type"
        },
        {
          "level": 3,
          "title": "type",
          "slug": "type"
        },
        {
          "level": 3,
          "title": "Extra",
          "slug": "extra"
        },
        {
          "level": 2,
          "title": "实战优化思路",
          "slug": "实战优化思路"
        }
      ],
      "lastUpdated": "2024/3/11 上午9:57:53",
      "lastUpdatedTimestamp": 1710122273000
    },
    {
      "title": "分布式存储系统——Ceph 部署使用",
      "frontmatter": {
        "title": "分布式存储系统——Ceph 部署使用",
        "date": "2023-12-25T00:00:00.000Z",
        "author": "Cleaner",
        "categories": [
          "后端"
        ],
        "tags": [
          "Ceph"
        ],
        "readingShow": "top"
      },
      "regularPath": "/backend/work/ceph.html",
      "relativePath": "backend/work/ceph.md",
      "key": "v-5acd688a",
      "path": "/backend/work/ceph.html",
      "headers": [
        {
          "level": 2,
          "title": "Ceph 介绍",
          "slug": "ceph-介绍"
        },
        {
          "level": 2,
          "title": "Ceph 集群搭建",
          "slug": "ceph-集群搭建"
        },
        {
          "level": 3,
          "title": "部署环境",
          "slug": "部署环境"
        },
        {
          "level": 3,
          "title": "拉取镜像",
          "slug": "拉取镜像"
        },
        {
          "level": 3,
          "title": "启动 mon 容器",
          "slug": "启动-mon-容器"
        },
        {
          "level": 3,
          "title": "启动 osd 容器",
          "slug": "启动-osd-容器"
        },
        {
          "level": 3,
          "title": "启动 mds 容器",
          "slug": "启动-mds-容器"
        },
        {
          "level": 3,
          "title": "启动 rgw 容器",
          "slug": "启动-rgw-容器"
        },
        {
          "level": 3,
          "title": "启动 mgr 容器",
          "slug": "启动-mgr-容器"
        },
        {
          "level": 3,
          "title": "安装 Dashboard 管理后台",
          "slug": "安装-dashboard-管理后台"
        },
        {
          "level": 2,
          "title": "创建用户 和 bucket",
          "slug": "创建用户-和-bucket"
        },
        {
          "level": 2,
          "title": "问题",
          "slug": "问题"
        },
        {
          "level": 2,
          "title": "参考文档",
          "slug": "参考文档"
        }
      ],
      "lastUpdated": "2024/1/16 下午4:38:59",
      "lastUpdatedTimestamp": 1705394339000
    },
    {
      "title": "使用 Poi-tl 类库实现 Echarts 图表 + 前端表格导出到 Word 文档",
      "frontmatter": {
        "title": "使用 Poi-tl 类库实现 Echarts 图表 + 前端表格导出到 Word 文档",
        "date": "2023-06-11T00:00:00.000Z",
        "author": "Cleaner",
        "categories": [
          "后端"
        ],
        "tags": [
          "Poi"
        ],
        "readingShow": "top"
      },
      "regularPath": "/backend/work/poi.html",
      "relativePath": "backend/work/poi.md",
      "key": "v-091f4df9",
      "path": "/backend/work/poi.html",
      "headers": [
        {
          "level": 2,
          "title": "前言",
          "slug": "前言"
        },
        {
          "level": 2,
          "title": "图表导出",
          "slug": "图表导出"
        },
        {
          "level": 3,
          "title": "引入依赖",
          "slug": "引入依赖"
        },
        {
          "level": 3,
          "title": "准备 Word 模板",
          "slug": "准备-word-模板"
        },
        {
          "level": 3,
          "title": "编码实现",
          "slug": "编码实现"
        },
        {
          "level": 2,
          "title": "表格导出",
          "slug": "表格导出"
        },
        {
          "level": 3,
          "title": "Word 模板调整",
          "slug": "word-模板调整"
        },
        {
          "level": 3,
          "title": "编码实现",
          "slug": "编码实现-2"
        },
        {
          "level": 2,
          "title": "问题",
          "slug": "问题"
        }
      ],
      "lastUpdated": "2023/12/20 下午3:12:16",
      "lastUpdatedTimestamp": 1703056336000
    },
    {
      "title": "企业级在线办公套件——OnlyOffice Workspace 部署使用",
      "frontmatter": {
        "title": "企业级在线办公套件——OnlyOffice Workspace 部署使用",
        "date": "2023-10-18T00:00:00.000Z",
        "author": "Cleaner",
        "categories": [
          "后端"
        ],
        "tags": [
          "OnlyOffice"
        ],
        "readingShow": "top"
      },
      "regularPath": "/backend/work/onlyoffice.html",
      "relativePath": "backend/work/onlyoffice.md",
      "key": "v-165bc73b",
      "path": "/backend/work/onlyoffice.html",
      "headers": [
        {
          "level": 2,
          "title": "前言",
          "slug": "前言"
        },
        {
          "level": 2,
          "title": "部署",
          "slug": "部署"
        },
        {
          "level": 3,
          "title": "服务器要求",
          "slug": "服务器要求"
        },
        {
          "level": 3,
          "title": "创建网络",
          "slug": "创建网络"
        },
        {
          "level": 3,
          "title": "MySQL",
          "slug": "mysql"
        },
        {
          "level": 3,
          "title": "Document Server",
          "slug": "document-server"
        },
        {
          "level": 3,
          "title": "Control Panel",
          "slug": "control-panel"
        },
        {
          "level": 3,
          "title": "Community Server",
          "slug": "community-server"
        },
        {
          "level": 2,
          "title": "使用",
          "slug": "使用"
        },
        {
          "level": 3,
          "title": "邮件添加账户",
          "slug": "邮件添加账户"
        },
        {
          "level": 2,
          "title": "Vue 集成 Document Server",
          "slug": "vue-集成-document-server"
        },
        {
          "level": 2,
          "title": "问题",
          "slug": "问题"
        },
        {
          "level": 3,
          "title": "Community Server 启动失败",
          "slug": "community-server-启动失败"
        },
        {
          "level": 3,
          "title": "文档安全令牌未正确形成",
          "slug": "文档安全令牌未正确形成"
        },
        {
          "level": 3,
          "title": "Document Server 20 人使用限制",
          "slug": "document-server-20-人使用限制"
        }
      ],
      "lastUpdated": "2023/12/20 上午10:50:10",
      "lastUpdatedTimestamp": 1703040610000
    },
    {
      "title": "Update 未加索引导致的微服务模块不可用",
      "frontmatter": {
        "title": "Update 未加索引导致的微服务模块不可用",
        "date": "2023-06-14T00:00:00.000Z",
        "author": "Cleaner",
        "categories": [
          "后端"
        ],
        "tags": [
          "MySQL"
        ],
        "readingShow": "top"
      },
      "regularPath": "/backend/work/practice.html",
      "relativePath": "backend/work/practice.md",
      "key": "v-2ab2a5ca",
      "path": "/backend/work/practice.html",
      "headers": [
        {
          "level": 2,
          "title": "前言",
          "slug": "前言"
        },
        {
          "level": 2,
          "title": "错误排查",
          "slug": "错误排查"
        },
        {
          "level": 3,
          "title": "查看日志",
          "slug": "查看日志"
        },
        {
          "level": 3,
          "title": "连接数据库",
          "slug": "连接数据库"
        },
        {
          "level": 2,
          "title": "问题定位&解决",
          "slug": "问题定位-解决"
        },
        {
          "level": 2,
          "title": "问题",
          "slug": "问题"
        },
        {
          "level": 2,
          "title": "末尾",
          "slug": "末尾"
        }
      ],
      "lastUpdated": "2023/12/20 下午3:12:16",
      "lastUpdatedTimestamp": 1703056336000
    },
    {
      "title": "使用 Axis 调用 WebService 服务接口",
      "frontmatter": {
        "title": "使用 Axis 调用 WebService 服务接口",
        "date": "2023-12-20T00:00:00.000Z",
        "author": "Cleaner",
        "categories": [
          "后端"
        ],
        "tags": [
          "WebService"
        ],
        "readingShow": "top"
      },
      "regularPath": "/backend/work/webservice.html",
      "relativePath": "backend/work/webservice.md",
      "key": "v-2a4b324a",
      "path": "/backend/work/webservice.html",
      "headers": [
        {
          "level": 2,
          "title": "前言",
          "slug": "前言"
        },
        {
          "level": 2,
          "title": "实现",
          "slug": "实现"
        },
        {
          "level": 3,
          "title": "引入依赖",
          "slug": "引入依赖"
        },
        {
          "level": 3,
          "title": "代码实现",
          "slug": "代码实现"
        },
        {
          "level": 2,
          "title": "说明",
          "slug": "说明"
        }
      ],
      "lastUpdated": "2024/1/29 下午2:35:44",
      "lastUpdatedTimestamp": 1706510144000
    },
    {
      "title": "JSX 实现 Element-ui 表格列动态渲染",
      "frontmatter": {
        "title": "JSX 实现 Element-ui 表格列动态渲染",
        "date": "2024-03-07T00:00:00.000Z",
        "author": "Cleaner",
        "categories": [
          "前端"
        ],
        "tags": [
          "Vue"
        ],
        "readingShow": "top"
      },
      "regularPath": "/frontend/vue/jsx.html",
      "relativePath": "frontend/vue/jsx.md",
      "key": "v-4fda8722",
      "path": "/frontend/vue/jsx.html",
      "lastUpdated": "2024/3/7 下午4:23:13",
      "lastUpdatedTimestamp": 1709799793000
    },
    {
      "title": "流式数据接收+打字机效果展示",
      "frontmatter": {
        "title": "流式数据接收+打字机效果展示",
        "date": "2024-03-07T00:00:00.000Z",
        "author": "Cleaner",
        "categories": [
          "前端"
        ],
        "tags": [
          "Vue"
        ],
        "readingShow": "top"
      },
      "regularPath": "/frontend/vue/stream.html",
      "relativePath": "frontend/vue/stream.md",
      "key": "v-790c0355",
      "path": "/frontend/vue/stream.html",
      "lastUpdated": "2024/3/7 下午4:23:13",
      "lastUpdatedTimestamp": 1709799793000
    },
    {
      "title": "使用 VuePress + GitHub Pages + GitHub Actions 搭建个人博客",
      "frontmatter": {
        "title": "使用 VuePress + GitHub Pages + GitHub Actions 搭建个人博客",
        "date": "2023-06-08T00:00:00.000Z",
        "author": "Cleaner",
        "categories": [
          "前端"
        ],
        "tags": [
          "VuePress"
        ],
        "readingShow": "top"
      },
      "regularPath": "/frontend/vuepress/VuePressOne.html",
      "relativePath": "frontend/vuepress/VuePressOne.md",
      "key": "v-5b9558ca",
      "path": "/frontend/vuepress/VuePressOne.html",
      "headers": [
        {
          "level": 2,
          "title": "新建代码仓库",
          "slug": "新建代码仓库"
        },
        {
          "level": 2,
          "title": "VuePress",
          "slug": "vuepress"
        },
        {
          "level": 3,
          "title": "项目初始化",
          "slug": "项目初始化"
        },
        {
          "level": 3,
          "title": "配置",
          "slug": "配置"
        },
        {
          "level": 3,
          "title": "运行",
          "slug": "运行"
        },
        {
          "level": 2,
          "title": "GitHub Pages",
          "slug": "github-pages"
        },
        {
          "level": 2,
          "title": "GitHub Actions",
          "slug": "github-actions"
        },
        {
          "level": 3,
          "title": "新增 Access Token",
          "slug": "新增-access-token"
        },
        {
          "level": 3,
          "title": "创建 Secrets",
          "slug": "创建-secrets"
        },
        {
          "level": 3,
          "title": "创建任务文件",
          "slug": "创建任务文件"
        },
        {
          "level": 2,
          "title": "验证",
          "slug": "验证"
        },
        {
          "level": 2,
          "title": "问题",
          "slug": "问题"
        }
      ],
      "lastUpdated": "2023/12/20 下午3:12:16",
      "lastUpdatedTimestamp": 1703056336000
    },
    {
      "title": "其他问题汇总",
      "frontmatter": {
        "title": "其他问题汇总",
        "date": "2024-03-07T00:00:00.000Z",
        "author": "Cleaner",
        "categories": [
          "前端"
        ],
        "tags": [
          "Vue"
        ],
        "readingShow": "top"
      },
      "regularPath": "/frontend/vue/questions.html",
      "relativePath": "frontend/vue/questions.md",
      "key": "v-4e38efb3",
      "path": "/frontend/vue/questions.html",
      "headers": [
        {
          "level": 2,
          "title": "v-html 标签失效",
          "slug": "v-html-标签失效"
        }
      ],
      "lastUpdated": "2024/3/7 下午4:23:13",
      "lastUpdatedTimestamp": 1709799793000
    },
    {
      "title": "VuePress + GitHub Pages 自定义域名",
      "frontmatter": {
        "title": "VuePress + GitHub Pages 自定义域名",
        "date": "2023-06-18T00:00:00.000Z",
        "author": "Cleaner",
        "categories": [
          "前端"
        ],
        "tags": [
          "VuePress"
        ],
        "readingShow": "top"
      },
      "regularPath": "/frontend/vuepress/VuePressThree.html",
      "relativePath": "frontend/vuepress/VuePressThree.md",
      "key": "v-921ea9ca",
      "path": "/frontend/vuepress/VuePressThree.html",
      "headers": [
        {
          "level": 2,
          "title": "域名",
          "slug": "域名"
        },
        {
          "level": 3,
          "title": "申请",
          "slug": "申请"
        },
        {
          "level": 3,
          "title": "配置",
          "slug": "配置"
        },
        {
          "level": 2,
          "title": "GitHub Pages 设置",
          "slug": "github-pages-设置"
        },
        {
          "level": 2,
          "title": "GitHub Actions 配置",
          "slug": "github-actions-配置"
        },
        {
          "level": 2,
          "title": "问题",
          "slug": "问题"
        }
      ],
      "lastUpdated": "2023/12/20 下午3:12:16",
      "lastUpdatedTimestamp": 1703056336000
    },
    {
      "title": "VuePress 个人博客美化：vuepress-theme-reco 主题使用",
      "frontmatter": {
        "title": "VuePress 个人博客美化：vuepress-theme-reco 主题使用",
        "date": "2023-06-08T00:00:00.000Z",
        "author": "Cleaner",
        "categories": [
          "前端"
        ],
        "tags": [
          "VuePress"
        ],
        "readingShow": "top"
      },
      "regularPath": "/frontend/vuepress/VuePressTwo.html",
      "relativePath": "frontend/vuepress/VuePressTwo.md",
      "key": "v-6ffbb6db",
      "path": "/frontend/vuepress/VuePressTwo.html",
      "headers": [
        {
          "level": 2,
          "title": "前言",
          "slug": "前言"
        },
        {
          "level": 2,
          "title": "项目目录",
          "slug": "项目目录"
        },
        {
          "level": 2,
          "title": "使用主题",
          "slug": "使用主题"
        },
        {
          "level": 2,
          "title": "全局配置",
          "slug": "全局配置"
        },
        {
          "level": 2,
          "title": "首页配置",
          "slug": "首页配置"
        },
        {
          "level": 2,
          "title": "Front Matter",
          "slug": "front-matter"
        },
        {
          "level": 2,
          "title": "添加 iconfont 图标",
          "slug": "添加-iconfont-图标"
        },
        {
          "level": 2,
          "title": "定制样式",
          "slug": "定制样式"
        },
        {
          "level": 2,
          "title": "插件",
          "slug": "插件"
        },
        {
          "level": 3,
          "title": "back-to-top",
          "slug": "back-to-top"
        },
        {
          "level": 3,
          "title": "commonts",
          "slug": "commonts"
        },
        {
          "level": 3,
          "title": "pagination",
          "slug": "pagination"
        },
        {
          "level": 3,
          "title": "PWA",
          "slug": "pwa"
        },
        {
          "level": 3,
          "title": "copy",
          "slug": "copy"
        },
        {
          "level": 3,
          "title": "sitemap",
          "slug": "sitemap"
        },
        {
          "level": 2,
          "title": "问题",
          "slug": "问题"
        },
        {
          "level": 2,
          "title": "末尾",
          "slug": "末尾"
        }
      ],
      "lastUpdated": "2024/1/29 下午2:35:44",
      "lastUpdatedTimestamp": 1706510144000
    },
    {
      "title": "大语言模型 InternLM2（书生·浦语）",
      "frontmatter": {
        "title": "大语言模型 InternLM2（书生·浦语）",
        "date": "2024-01-29T00:00:00.000Z",
        "author": "Cleaner",
        "categories": [
          "人工智能"
        ],
        "tags": [
          "LLM"
        ],
        "readingShow": "top"
      },
      "regularPath": "/llm/InternLM2.html",
      "relativePath": "llm/InternLM2.md",
      "key": "v-9e33fd64",
      "path": "/llm/InternLM2.html",
      "headers": [
        {
          "level": 2,
          "title": "介绍",
          "slug": "介绍"
        },
        {
          "level": 2,
          "title": "环境准备",
          "slug": "环境准备"
        },
        {
          "level": 2,
          "title": "模型部署&使用",
          "slug": "模型部署-使用"
        },
        {
          "level": 3,
          "title": "页面交互方式",
          "slug": "页面交互方式"
        },
        {
          "level": 3,
          "title": "代码方式",
          "slug": "代码方式"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        },
        {
          "level": 2,
          "title": "末尾",
          "slug": "末尾"
        }
      ],
      "lastUpdated": "2024/2/7 下午3:14:56",
      "lastUpdatedTimestamp": 1707290096000
    },
    {
      "title": "留言板",
      "frontmatter": {
        "title": "留言板",
        "date": "2023-07-25T00:00:00.000Z",
        "author": "Cleaner",
        "readingShow": false,
        "pageClass": "message-board"
      },
      "regularPath": "/message-board.html",
      "relativePath": "message-board.md",
      "key": "v-6a783e8a",
      "path": "/message-board.html",
      "lastUpdated": "2024/1/16 下午4:38:59",
      "lastUpdatedTimestamp": 1705394339000
    },
    {
      "title": "大语言模型基础知识",
      "frontmatter": {
        "title": "大语言模型基础知识",
        "date": "2024-06-17T00:00:00.000Z",
        "author": "Cleaner",
        "categories": [
          "人工智能"
        ],
        "tags": [
          "LLM"
        ],
        "readingShow": "top"
      },
      "regularPath": "/llm/basicOne.html",
      "relativePath": "llm/basicOne.md",
      "key": "v-36e6c066",
      "path": "/llm/basicOne.html",
      "headers": [
        {
          "level": 2,
          "title": "一、大语言模型发展历程",
          "slug": "一、大语言模型发展历程"
        },
        {
          "level": 3,
          "title": "统计语言模型（Statistical Language Model, SLM）",
          "slug": "统计语言模型-statistical-language-model-slm"
        },
        {
          "level": 3,
          "title": "神经语言模型（Neural Language Model, NLM）",
          "slug": "神经语言模型-neural-language-model-nlm"
        },
        {
          "level": 3,
          "title": "预训练语言模型（Pre-trained Language Model, PLM）",
          "slug": "预训练语言模型-pre-trained-language-model-plm"
        },
        {
          "level": 3,
          "title": "大语言模型（Large Language Model, LLM）",
          "slug": "大语言模型-large-language-model-llm"
        },
        {
          "level": 2,
          "title": "二、大语言模型构建过程",
          "slug": "二、大语言模型构建过程"
        },
        {
          "level": 3,
          "title": "预训练",
          "slug": "预训练"
        },
        {
          "level": 3,
          "title": "指令微调",
          "slug": "指令微调"
        },
        {
          "level": 3,
          "title": "人类对齐",
          "slug": "人类对齐"
        },
        {
          "level": 2,
          "title": "三、大语言模型使用",
          "slug": "三、大语言模型使用"
        },
        {
          "level": 3,
          "title": "低资源部署策略",
          "slug": "低资源部署策略"
        },
        {
          "level": 3,
          "title": "提示学习",
          "slug": "提示学习"
        },
        {
          "level": 3,
          "title": "智能体",
          "slug": "智能体"
        }
      ],
      "lastUpdated": "2024/6/17 下午6:19:50",
      "lastUpdatedTimestamp": 1718619590000
    },
    {
      "title": "树洞",
      "frontmatter": {
        "title": "树洞",
        "date": "2023-10-22T00:00:00.000Z",
        "author": "Cleaner",
        "readingShow": false,
        "pageClass": "treeholes"
      },
      "regularPath": "/other/treeholes.html",
      "relativePath": "other/treeholes.md",
      "key": "v-04e7d924",
      "path": "/other/treeholes.html",
      "lastUpdated": "2024/7/19 上午10:16:00",
      "lastUpdatedTimestamp": 1721355360000
    },
    {
      "frontmatter": {
        "readingShow": false
      },
      "regularPath": "/other/navigate.html",
      "relativePath": "other/navigate.md",
      "key": "v-1547fefa",
      "path": "/other/navigate.html",
      "lastUpdated": "2024/7/19 上午10:16:00",
      "lastUpdatedTimestamp": 1721355360000
    },
    {
      "title": "CentOS",
      "frontmatter": {
        "title": "CentOS",
        "date": "2024-03-11T00:00:00.000Z",
        "author": "Cleaner",
        "categories": [
          "工具"
        ],
        "tags": [
          "CentOS"
        ],
        "readingShow": "top"
      },
      "regularPath": "/tool/centos.html",
      "relativePath": "tool/centos.md",
      "key": "v-75cbd388",
      "path": "/tool/centos.html",
      "headers": [
        {
          "level": 2,
          "title": "防火墙",
          "slug": "防火墙"
        },
        {
          "level": 2,
          "title": "显存",
          "slug": "显存"
        },
        {
          "level": 2,
          "title": "问题汇总",
          "slug": "问题汇总"
        }
      ],
      "lastUpdated": "2024/3/11 上午9:57:53",
      "lastUpdatedTimestamp": 1710122273000
    },
    {
      "title": "Git",
      "frontmatter": {
        "title": "Git",
        "date": "2023-09-05T00:00:00.000Z",
        "author": "Cleaner",
        "categories": [
          "工具"
        ],
        "tags": [
          "Git"
        ],
        "readingShow": "top"
      },
      "regularPath": "/tool/git.html",
      "relativePath": "tool/git.md",
      "key": "v-24218ec4",
      "path": "/tool/git.html",
      "headers": [
        {
          "level": 2,
          "title": "Git 常用命令",
          "slug": "git-常用命令"
        },
        {
          "level": 2,
          "title": "项目开发中的 Git 规范",
          "slug": "项目开发中的-git-规范"
        },
        {
          "level": 3,
          "title": "git commit  提交信息规范",
          "slug": "git-commit-提交信息规范"
        },
        {
          "level": 3,
          "title": "代码提交流程",
          "slug": "代码提交流程"
        }
      ],
      "lastUpdated": "2024/3/11 上午9:57:53",
      "lastUpdatedTimestamp": 1710122273000
    },
    {
      "frontmatter": {
        "layout": "Tags",
        "title": "Tags",
        "readingShow": "top"
      },
      "regularPath": "/tag/",
      "key": "v-b1564aac",
      "path": "/tag/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterKey",
        "title": "Categories",
        "readingShow": "top"
      },
      "regularPath": "/categories/",
      "key": "v-ef9325c4",
      "path": "/categories/"
    },
    {
      "frontmatter": {
        "layout": "TimeLines",
        "title": "Timeline",
        "readingShow": "top"
      },
      "regularPath": "/timeline/",
      "key": "v-6319eb4e",
      "path": "/timeline/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "Docker Tags",
        "readingShow": "top"
      },
      "regularPath": "/tag/Docker/",
      "key": "v-83bebff6",
      "path": "/tag/Docker/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "Micorservice Tags",
        "readingShow": "top"
      },
      "regularPath": "/tag/Micorservice/",
      "key": "v-7a62bdfa",
      "path": "/tag/Micorservice/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "EasyExcel Tags",
        "readingShow": "top"
      },
      "regularPath": "/tag/EasyExcel/",
      "key": "v-5ba5b544",
      "path": "/tag/EasyExcel/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "MySQL Tags",
        "readingShow": "top"
      },
      "regularPath": "/tag/MySQL/",
      "key": "v-dc3c2992",
      "path": "/tag/MySQL/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "Ceph Tags",
        "readingShow": "top"
      },
      "regularPath": "/tag/Ceph/",
      "key": "v-18c9fdea",
      "path": "/tag/Ceph/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "Poi Tags",
        "readingShow": "top"
      },
      "regularPath": "/tag/Poi/",
      "key": "v-324cfe22",
      "path": "/tag/Poi/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "OnlyOffice Tags",
        "readingShow": "top"
      },
      "regularPath": "/tag/OnlyOffice/",
      "key": "v-364eb69d",
      "path": "/tag/OnlyOffice/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "WebService Tags",
        "readingShow": "top"
      },
      "regularPath": "/tag/WebService/",
      "key": "v-9c29eaf8",
      "path": "/tag/WebService/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "Vue Tags",
        "readingShow": "top"
      },
      "regularPath": "/tag/Vue/",
      "key": "v-32475d9a",
      "path": "/tag/Vue/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "VuePress Tags",
        "readingShow": "top"
      },
      "regularPath": "/tag/VuePress/",
      "key": "v-5e08fc30",
      "path": "/tag/VuePress/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "LLM Tags",
        "readingShow": "top"
      },
      "regularPath": "/tag/LLM/",
      "key": "v-3251aea8",
      "path": "/tag/LLM/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "CentOS Tags",
        "readingShow": "top"
      },
      "regularPath": "/tag/CentOS/",
      "key": "v-78c8b219",
      "path": "/tag/CentOS/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "Git Tags",
        "readingShow": "top"
      },
      "regularPath": "/tag/Git/",
      "key": "v-32555732",
      "path": "/tag/Git/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "后端 Categories",
        "readingShow": "top"
      },
      "regularPath": "/categories/%E5%90%8E%E7%AB%AF/",
      "key": "v-12afc5a1",
      "path": "/categories/后端/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "前端 Categories",
        "readingShow": "top"
      },
      "regularPath": "/categories/%E5%89%8D%E7%AB%AF/",
      "key": "v-14bbbf36",
      "path": "/categories/前端/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "人工智能 Categories",
        "readingShow": "top"
      },
      "regularPath": "/categories/%E4%BA%BA%E5%B7%A5%E6%99%BA%E8%83%BD/",
      "key": "v-4e573672",
      "path": "/categories/人工智能/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "工具 Categories",
        "readingShow": "top"
      },
      "regularPath": "/categories/%E5%B7%A5%E5%85%B7/",
      "key": "v-7f958298",
      "path": "/categories/工具/"
    }
  ],
  "themeConfig": {
    "type": "blog",
    "autohor": "Cleaner",
    "domain": "cleaner.love",
    "startYear": "2023",
    "authorAvatar": "/avator.jpg",
    "search": true,
    "searchMaxSuggestions": 10,
    "subSidebar": "auto",
    "sidebarDepth": 1,
    "noFoundPageByTencent": false,
    "modePicker": false,
    "lastUpdated": "更新时间",
    "timezoneOffset": 28800000,
    "blogConfig": {
      "socialLinks": [
        {
          "icon": "reco-github",
          "link": "https://github.com/SongJian-99"
        },
        {
          "icon": "reco-juejin",
          "link": "https://juejin.cn/user/1517786987244510"
        }
      ]
    },
    "nav": [
      {
        "text": "导航",
        "link": "/other/navigate",
        "icon": "iconfont icon-navigate"
      },
      {
        "text": "前端",
        "icon": "iconfont icon-frontend",
        "items": [
          {
            "text": "VuePress",
            "link": "/frontend/vuepress/VuePressOne.md"
          },
          {
            "text": "Vue",
            "link": "/frontend/vue/jsx.md"
          }
        ]
      },
      {
        "text": "Docker",
        "link": "/backend/docker/Web",
        "icon": "iconfont icon-docker"
      },
      {
        "text": "MySQL",
        "link": "/backend/mysql/explain",
        "icon": "iconfont icon-mysql"
      },
      {
        "text": "工作",
        "link": "/backend/work/poi",
        "icon": "iconfont icon-work"
      },
      {
        "text": "微服务",
        "link": "/backend/microservice/twelve-factor",
        "icon": "iconfont icon-microservice"
      },
      {
        "text": "大语言模型",
        "link": "/llm/basicOne",
        "icon": "iconfont icon-ai"
      },
      {
        "text": "工具",
        "link": "/tool/git",
        "icon": "iconfont icon-tools"
      },
      {
        "text": "其他",
        "icon": "reco-other",
        "items": [
          {
            "text": "树洞",
            "link": "/other/treeholes"
          }
        ]
      },
      {
        "text": "时间轴",
        "link": "/timeLine/",
        "icon": "reco-date"
      }
    ],
    "sidebar": {
      "/backend/docker/": [
        {
          "title": "Docker 应用",
          "collapsable": false,
          "children": [
            {
              "title": "使用 Dockerfile + Docker Compose 部署 Web 项目",
              "path": "/backend/docker/Web"
            },
            {
              "title": "使用 Docker Compose 部署 Elasticsearch + Kibana",
              "path": "/backend/docker/Elasticsearch"
            }
          ]
        }
      ],
      "/backend/microservice/": [
        {
          "title": "微服务理论知识",
          "collapsable": false,
          "children": [
            {
              "title": "微服务架构中实施应用开发的十二要素",
              "path": "/backend/microservice/twelve-factor"
            }
          ]
        }
      ],
      "/backend/work/": [
        {
          "title": "工作实践",
          "collapsable": false,
          "children": [
            {
              "title": "使用 Poi-tl 类库实现 Echarts 图表 + 前端表格导出到 Word 文档",
              "path": "/backend/work/poi"
            },
            {
              "title": "Update 未加索引导致的微服务模块不可用",
              "path": "/backend/work/practice"
            },
            {
              "title": "企业级在线办公套件——OnlyOffice Workspace 部署使用",
              "path": "/backend/work/onlyoffice"
            },
            {
              "title": "使用 Axis 调用 WebService 服务接口",
              "path": "/backend/work/webservice"
            },
            {
              "title": "分布式存储系统——Ceph 部署使用",
              "path": "/backend/work/ceph"
            },
            {
              "title": "EasyExcel 导出多张图片",
              "path": "/backend/work/easyexcel"
            }
          ]
        }
      ],
      "/backend/mysql": [
        {
          "title": "MySQL",
          "collapsable": false,
          "children": [
            {
              "title": "SQL 执行计划分析",
              "path": "/backend/mysql/explain"
            }
          ]
        }
      ],
      "/frontend": [
        {
          "title": "VuePress 使用实践",
          "collapsable": false,
          "children": [
            {
              "title": "使用 VuePress + GitHub Pages + GitHub Actions 搭建个人博客",
              "path": "/frontend/vuepress/VuePressOne"
            },
            {
              "title": "VuePress 个人博客美化：vuepress-theme-reco 主题使用",
              "path": "/frontend/vuepress/VuePressTwo"
            },
            {
              "title": "VuePress + GitHub Pages 自定义域名",
              "path": "/frontend/vuepress/VuePressThree"
            }
          ]
        },
        {
          "title": "Vue 使用实践",
          "collapsable": false,
          "children": [
            {
              "title": "JSX 实现 Element-ui 表格列动态渲染",
              "path": "/frontend/vue/jsx"
            },
            {
              "title": "流式数据接收+打字机效果展示",
              "path": "/frontend/vue/stream"
            },
            {
              "title": "其他问题汇总",
              "path": "/frontend/vue/questions"
            }
          ]
        }
      ],
      "/tool": [
        {
          "title": "Git 使用实践",
          "collapsable": false,
          "children": [
            {
              "title": "Git 常用命令",
              "path": "/tool/git"
            }
          ]
        },
        {
          "title": "CentOS 使用实践",
          "collapsable": false,
          "children": [
            {
              "title": "CentOS 知识汇总",
              "path": "/tool/centos"
            }
          ]
        }
      ],
      "/llm": [
        {
          "title": "大语言模型基础",
          "collapsable": false,
          "children": [
            {
              "title": "发展历程、构建过程及如何使用",
              "path": "/llm/basicOne"
            }
          ]
        },
        {
          "title": "大语言模型使用",
          "collapsable": false,
          "children": [
            {
              "title": "InternLM2（书生·浦语）",
              "path": "/llm/InternLM2"
            }
          ]
        }
      ]
    }
  },
  "locales": {
    "/": {
      "lang": "zh-CN",
      "path": "/"
    }
  }
}