/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "Cleaner",
  "description": "Cleaner's blog",
  "base": "/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/favicon.ico"
      }
    ],
    [
      "meta",
      {
        "name": "viewport",
        "content": "width=device-width,initial-scale=1,user-scalable=no"
      }
    ]
  ],
  "pages": [
    {
      "title": "首页",
      "frontmatter": {
        "home": true,
        "title": "首页",
        "author": "Cleaner",
        "heroText": null,
        "tagline": null,
        "heroImage": "/logo.jpg",
        "heroImageStyle": {
          "maxWidth": "450px",
          "display": "block",
          "margin": "-12rem auto 1.5rem",
          "boxShadow": "0 5px 18px rgba(0,0,0,0.2)"
        }
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-9280c340",
      "path": "/",
      "lastUpdated": "2023/6/6 下午3:26:53",
      "lastUpdatedTimestamp": 1686036413000
    },
    {
      "frontmatter": {},
      "regularPath": "/books/bookList.html",
      "relativePath": "books/bookList.md",
      "key": "v-7a04bb7c",
      "path": "/books/bookList.html",
      "lastUpdated": "2023/4/21 上午9:53:30",
      "lastUpdatedTimestamp": 1682042010000
    },
    {
      "title": "关圣帝君觉世真经",
      "frontmatter": {
        "title": "关圣帝君觉世真经",
        "date": "2023-04-20T00:00:00.000Z",
        "categories": [
          "传统文化"
        ],
        "tags": [
          "道"
        ]
      },
      "regularPath": "/books/%E5%85%B3%E5%9C%A3%E5%B8%9D%E5%90%9B%E8%A7%89%E4%B8%96%E7%9C%9F%E7%BB%8F.html",
      "relativePath": "books/关圣帝君觉世真经.md",
      "key": "v-2d92859e",
      "path": "/books/%E5%85%B3%E5%9C%A3%E5%B8%9D%E5%90%9B%E8%A7%89%E4%B8%96%E7%9C%9F%E7%BB%8F.html",
      "lastUpdated": "2023/4/21 上午9:53:30",
      "lastUpdatedTimestamp": 1682042010000
    },
    {
      "title": "太上老君说常清静经",
      "frontmatter": {
        "title": "太上老君说常清静经",
        "date": "2023-04-20T00:00:00.000Z",
        "categories": [
          "传统文化"
        ],
        "tags": [
          "道"
        ]
      },
      "regularPath": "/books/%E5%A4%AA%E4%B8%8A%E8%80%81%E5%90%9B%E8%AF%B4%E5%B8%B8%E6%B8%85%E9%9D%99%E7%BB%8F.html",
      "relativePath": "books/太上老君说常清静经.md",
      "key": "v-3ec94b9a",
      "path": "/books/%E5%A4%AA%E4%B8%8A%E8%80%81%E5%90%9B%E8%AF%B4%E5%B8%B8%E6%B8%85%E9%9D%99%E7%BB%8F.html",
      "lastUpdated": "2023/4/21 上午9:53:30",
      "lastUpdatedTimestamp": 1682042010000
    },
    {
      "title": "使用 Docker Compose 部署 Elasticsearch + Kibana",
      "frontmatter": {
        "title": "使用 Docker Compose 部署 Elasticsearch + Kibana",
        "date": "2023-06-06T00:00:00.000Z",
        "isShowComments": true,
        "categories": [
          "后端"
        ],
        "tags": [
          "Docker"
        ]
      },
      "regularPath": "/docker/Elasticsearch.html",
      "relativePath": "docker/Elasticsearch.md",
      "key": "v-d8bc6e10",
      "path": "/docker/Elasticsearch.html",
      "headers": [
        {
          "level": 2,
          "title": "服务器目录结构",
          "slug": "服务器目录结构"
        },
        {
          "level": 2,
          "title": "部署 Elasticsearch 和 Kibana",
          "slug": "部署-elasticsearch-和-kibana"
        },
        {
          "level": 3,
          "title": "启动容器",
          "slug": "启动容器"
        },
        {
          "level": 3,
          "title": "设置登陆密码",
          "slug": "设置登陆密码"
        },
        {
          "level": 3,
          "title": "完整配置文件内容",
          "slug": "完整配置文件内容"
        },
        {
          "level": 2,
          "title": "Spring Boot 整合 Elasticsearch",
          "slug": "spring-boot-整合-elasticsearch"
        },
        {
          "level": 3,
          "title": "添加依赖",
          "slug": "添加依赖"
        },
        {
          "level": 3,
          "title": "添加配置",
          "slug": "添加配置"
        },
        {
          "level": 3,
          "title": "使用",
          "slug": "使用"
        },
        {
          "level": 2,
          "title": "问题",
          "slug": "问题"
        }
      ],
      "lastUpdated": "2023/6/7 下午6:47:03",
      "lastUpdatedTimestamp": 1686134823000
    },
    {
      "title": "素书",
      "frontmatter": {
        "title": "素书",
        "date": "2023-04-20T00:00:00.000Z",
        "categories": [
          "传统文化"
        ],
        "tags": [
          "道"
        ]
      },
      "regularPath": "/books/%E7%B4%A0%E4%B9%A6.html",
      "relativePath": "books/素书.md",
      "key": "v-cbbc8128",
      "path": "/books/%E7%B4%A0%E4%B9%A6.html",
      "headers": [
        {
          "level": 2,
          "title": "原始章第一",
          "slug": "原始章第一"
        },
        {
          "level": 2,
          "title": "正道章第二",
          "slug": "正道章第二"
        },
        {
          "level": 2,
          "title": "求人之志章第三",
          "slug": "求人之志章第三"
        },
        {
          "level": 2,
          "title": "本德宗道章第四",
          "slug": "本德宗道章第四"
        },
        {
          "level": 2,
          "title": "遵义章第五",
          "slug": "遵义章第五"
        },
        {
          "level": 2,
          "title": "安礼章第六",
          "slug": "安礼章第六"
        }
      ],
      "lastUpdated": "2023/4/21 上午9:53:30",
      "lastUpdatedTimestamp": 1682042010000
    },
    {
      "frontmatter": {},
      "regularPath": "/docker/preface.html",
      "relativePath": "docker/preface.md",
      "key": "v-100f049c",
      "path": "/docker/preface.html",
      "lastUpdated": "2023/6/6 下午3:26:53",
      "lastUpdatedTimestamp": 1686036413000
    },
    {
      "title": "使用 VuePress + GitHub Pages + GitHub Actions 搭建个人博客",
      "frontmatter": {
        "title": "使用 VuePress + GitHub Pages + GitHub Actions 搭建个人博客",
        "date": "2023-06-08T00:00:00.000Z",
        "isShowComments": true,
        "categories": [
          "前端"
        ],
        "tags": [
          "VuePress"
        ]
      },
      "regularPath": "/frontend/vuepress/VuePressOne.html",
      "relativePath": "frontend/vuepress/VuePressOne.md",
      "key": "v-5b9558ca",
      "path": "/frontend/vuepress/VuePressOne.html",
      "headers": [
        {
          "level": 2,
          "title": "新建代码仓库",
          "slug": "新建代码仓库"
        },
        {
          "level": 2,
          "title": "VuePress",
          "slug": "vuepress"
        },
        {
          "level": 3,
          "title": "项目初始化",
          "slug": "项目初始化"
        },
        {
          "level": 3,
          "title": "配置",
          "slug": "配置"
        },
        {
          "level": 3,
          "title": "运行",
          "slug": "运行"
        },
        {
          "level": 2,
          "title": "GitHub Pages",
          "slug": "github-pages"
        },
        {
          "level": 2,
          "title": "GitHub Actions",
          "slug": "github-actions"
        },
        {
          "level": 3,
          "title": "新增 Access Token",
          "slug": "新增-access-token"
        },
        {
          "level": 3,
          "title": "创建 Secrets",
          "slug": "创建-secrets"
        },
        {
          "level": 3,
          "title": "创建任务文件",
          "slug": "创建任务文件"
        },
        {
          "level": 2,
          "title": "验证",
          "slug": "验证"
        },
        {
          "level": 2,
          "title": "问题",
          "slug": "问题"
        }
      ]
    },
    {
      "title": "太乙金华宗旨",
      "frontmatter": {
        "title": "太乙金华宗旨",
        "date": "2023-04-20T00:00:00.000Z",
        "categories": [
          "传统文化"
        ],
        "tags": [
          "道"
        ]
      },
      "regularPath": "/books/%E5%A4%AA%E4%B9%99%E9%87%91%E5%8D%8E%E5%AE%97%E6%97%A8.html",
      "relativePath": "books/太乙金华宗旨.md",
      "key": "v-06af9d94",
      "path": "/books/%E5%A4%AA%E4%B9%99%E9%87%91%E5%8D%8E%E5%AE%97%E6%97%A8.html",
      "headers": [
        {
          "level": 2,
          "title": "自序",
          "slug": "自序"
        },
        {
          "level": 2,
          "title": "重序",
          "slug": "重序"
        },
        {
          "level": 2,
          "title": "天心第一",
          "slug": "天心第一"
        },
        {
          "level": 2,
          "title": "元神识神第二",
          "slug": "元神识神第二"
        },
        {
          "level": 2,
          "title": "回光守中第三",
          "slug": "回光守中第三"
        },
        {
          "level": 2,
          "title": "回光调息第四",
          "slug": "回光调息第四"
        },
        {
          "level": 2,
          "title": "回光差谬第五",
          "slug": "回光差谬第五"
        },
        {
          "level": 2,
          "title": "回光征验第六",
          "slug": "回光征验第六"
        },
        {
          "level": 2,
          "title": "回光活法第七",
          "slug": "回光活法第七"
        },
        {
          "level": 2,
          "title": "逍遥诀法第八",
          "slug": "逍遥诀法第八"
        },
        {
          "level": 2,
          "title": "百日立基第九",
          "slug": "百日立基第九"
        },
        {
          "level": 2,
          "title": "性光识光第十",
          "slug": "性光识光第十"
        },
        {
          "level": 2,
          "title": "坎离交媾第十一",
          "slug": "坎离交媾第十一"
        },
        {
          "level": 2,
          "title": "周天第十二",
          "slug": "周天第十二"
        },
        {
          "level": 2,
          "title": "劝世歌第十三",
          "slug": "劝世歌第十三"
        }
      ],
      "lastUpdated": "2023/4/21 上午9:53:30",
      "lastUpdatedTimestamp": 1682042010000
    },
    {
      "title": "使用 Dockerfile + Docker Compose 部署 Web 项目",
      "frontmatter": {
        "title": "使用 Dockerfile + Docker Compose 部署 Web 项目",
        "date": "2023-06-06T00:00:00.000Z",
        "isShowComments": true,
        "categories": [
          "后端"
        ],
        "tags": [
          "Docker"
        ]
      },
      "regularPath": "/docker/Web.html",
      "relativePath": "docker/Web.md",
      "key": "v-539ebe6c",
      "path": "/docker/Web.html",
      "headers": [
        {
          "level": 2,
          "title": "服务器目录结构",
          "slug": "服务器目录结构"
        },
        {
          "level": 2,
          "title": "数据库",
          "slug": "数据库"
        },
        {
          "level": 3,
          "title": "拉取 MySQL 镜像",
          "slug": "拉取-mysql-镜像"
        },
        {
          "level": 3,
          "title": "启动 MySQL 容器",
          "slug": "启动-mysql-容器"
        },
        {
          "level": 2,
          "title": "制作 JDK17 镜像",
          "slug": "制作-jdk17-镜像"
        },
        {
          "level": 3,
          "title": "下载 JDK",
          "slug": "下载-jdk"
        },
        {
          "level": 3,
          "title": "编写 Dockerfile 文件",
          "slug": "编写-dockerfile-文件"
        },
        {
          "level": 3,
          "title": "构建 JDK 镜像",
          "slug": "构建-jdk-镜像"
        },
        {
          "level": 2,
          "title": "后端",
          "slug": "后端"
        },
        {
          "level": 3,
          "title": "编写 Dockerfile 文件",
          "slug": "编写-dockerfile-文件-2"
        },
        {
          "level": 3,
          "title": "启动容器",
          "slug": "启动容器"
        },
        {
          "level": 2,
          "title": "前端",
          "slug": "前端"
        },
        {
          "level": 3,
          "title": "项目打包",
          "slug": "项目打包"
        },
        {
          "level": 3,
          "title": "编写 nginx.conf 配置文件",
          "slug": "编写-nginx-conf-配置文件"
        },
        {
          "level": 3,
          "title": "编写 Dockerfile 文件",
          "slug": "编写-dockerfile-文件-3"
        },
        {
          "level": 3,
          "title": "启动容器",
          "slug": "启动容器-2"
        },
        {
          "level": 2,
          "title": "问题",
          "slug": "问题"
        }
      ],
      "lastUpdated": "2023/6/6 下午3:26:53",
      "lastUpdatedTimestamp": 1686036413000
    },
    {
      "title": "VuePress 个人博客美化：vuepress-theme-reco 主题使用",
      "frontmatter": {
        "title": "VuePress 个人博客美化：vuepress-theme-reco 主题使用",
        "date": "2023-06-08T00:00:00.000Z",
        "isShowComments": true,
        "categories": [
          "前端"
        ],
        "tags": [
          "VuePress"
        ]
      },
      "regularPath": "/frontend/vuepress/VuePressTwo.html",
      "relativePath": "frontend/vuepress/VuePressTwo.md",
      "key": "v-6ffbb6db",
      "path": "/frontend/vuepress/VuePressTwo.html",
      "headers": [
        {
          "level": 2,
          "title": "前言",
          "slug": "前言"
        },
        {
          "level": 2,
          "title": "项目目录",
          "slug": "项目目录"
        },
        {
          "level": 2,
          "title": "使用主题",
          "slug": "使用主题"
        },
        {
          "level": 2,
          "title": "全局配置",
          "slug": "全局配置"
        },
        {
          "level": 2,
          "title": "首页配置",
          "slug": "首页配置"
        },
        {
          "level": 2,
          "title": "Front Matter",
          "slug": "front-matter"
        },
        {
          "level": 2,
          "title": "添加 iconfont 图标",
          "slug": "添加-iconfont-图标"
        },
        {
          "level": 2,
          "title": "定制样式",
          "slug": "定制样式"
        },
        {
          "level": 2,
          "title": "插件",
          "slug": "插件"
        },
        {
          "level": 3,
          "title": "back-to-top",
          "slug": "back-to-top"
        },
        {
          "level": 3,
          "title": "commonts",
          "slug": "commonts"
        },
        {
          "level": 2,
          "title": "末尾",
          "slug": "末尾"
        }
      ]
    },
    {
      "frontmatter": {
        "layout": "Tags",
        "title": "Tags"
      },
      "regularPath": "/tag/",
      "key": "v-b1564aac",
      "path": "/tag/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterKey",
        "title": "Categories"
      },
      "regularPath": "/categories/",
      "key": "v-ef9325c4",
      "path": "/categories/"
    },
    {
      "frontmatter": {
        "layout": "TimeLines",
        "title": "Timeline"
      },
      "regularPath": "/timeline/",
      "key": "v-6319eb4e",
      "path": "/timeline/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "道 Tags"
      },
      "regularPath": "/tag/%E9%81%93/",
      "key": "v-c7911d02",
      "path": "/tag/道/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "Docker Tags"
      },
      "regularPath": "/tag/Docker/",
      "key": "v-83bebff6",
      "path": "/tag/Docker/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "VuePress Tags"
      },
      "regularPath": "/tag/VuePress/",
      "key": "v-5e08fc30",
      "path": "/tag/VuePress/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "传统文化 Categories"
      },
      "regularPath": "/categories/%E4%BC%A0%E7%BB%9F%E6%96%87%E5%8C%96/",
      "key": "v-60cad880",
      "path": "/categories/传统文化/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "后端 Categories"
      },
      "regularPath": "/categories/%E5%90%8E%E7%AB%AF/",
      "key": "v-12afc5a1",
      "path": "/categories/后端/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "前端 Categories"
      },
      "regularPath": "/categories/%E5%89%8D%E7%AB%AF/",
      "key": "v-14bbbf36",
      "path": "/categories/前端/"
    }
  ],
  "themeConfig": {
    "type": "blog",
    "autohor": "Cleaner",
    "authorAvatar": "/avator.jpg",
    "search": true,
    "searchMaxSuggestions": 10,
    "subSidebar": "auto",
    "sidebarDepth": 1,
    "noFoundPageByTencent": false,
    "lastUpdated": "更新时间",
    "timezoneOffset": 28800000,
    "blogConfig": {
      "socialLinks": [
        {
          "icon": "reco-github",
          "link": "https://github.com/SongJian-99"
        }
      ]
    },
    "nav": [
      {
        "text": "前端",
        "icon": "iconfont icon-frontend",
        "items": [
          {
            "text": "VuePress",
            "link": "/frontend/vuepress/VuePressOne"
          }
        ]
      },
      {
        "text": "Docker",
        "link": "/docker/preface",
        "icon": "iconfont icon-docker"
      },
      {
        "text": "书籍",
        "link": "/books/bookList",
        "icon": "reco-document"
      },
      {
        "text": "时间轴",
        "link": "/timeLine/",
        "icon": "reco-date"
      }
    ],
    "sidebar": {
      "/books/": [
        {
          "title": "传统文化",
          "collapsable": true,
          "children": [
            {
              "title": "太乙金华宗旨",
              "path": "/books/太乙金华宗旨"
            },
            {
              "title": "太上老君说常清静经",
              "path": "/books/太上老君说常清静经"
            },
            {
              "title": "关圣帝君觉世真经",
              "path": "/books/关圣帝君觉世真经"
            },
            {
              "title": "素书",
              "path": "/books/素书"
            }
          ]
        }
      ],
      "/docker/": [
        {
          "title": "Docker 应用",
          "collapsable": true,
          "children": [
            {
              "title": "使用 Docker Compose 部署 Elasticsearch + Kibana",
              "path": "/docker/Elasticsearch"
            },
            {
              "title": "使用 Dockerfile + Docker Compose 部署 Web 项目",
              "path": "/docker/Web"
            }
          ]
        }
      ],
      "/frontend/vuepress": [
        {
          "title": "VuePress",
          "collapsable": true,
          "children": [
            {
              "title": "使用 VuePress + GitHub Pages + GitHub Actions 搭建个人博客",
              "path": "/frontend/vuepress/VuePressOne"
            },
            {
              "title": "VuePress 个人博客美化：vuepress-theme-reco 主题使用",
              "path": "/frontend/vuepress/VuePressTwo"
            }
          ]
        }
      ]
    },
    "valineConfig": {
      "appId": "qR1MgQXTGffUVgeTTM9Qnl3E-gzGzoHsz",
      "appKey": "OdwTWvfZsjbJIsBtQcgzc4eP",
      "showComment": false
    }
  },
  "locales": {
    "/": {
      "lang": "zh-CN",
      "path": "/"
    }
  }
}