/**
 * Generated by "@vuepress/plugin-blog"
 */
export default {
  "tags": {
    "Docker": {
      "key": "Docker",
      "scope": "tags",
      "path": "/tag/Docker/",
      "pageKeys": [
        "v-f6dcfe16",
        "v-65a62e07"
      ]
    },
    "MySQL": {
      "key": "MySQL",
      "scope": "tags",
      "path": "/tag/MySQL/",
      "pageKeys": [
        "v-15ca2d81",
        "v-2ab2a5ca"
      ]
    },
    "Micorservice": {
      "key": "Micorservice",
      "scope": "tags",
      "path": "/tag/Micorservice/",
      "pageKeys": [
        "v-1227ff87"
      ]
    },
    "Ceph": {
      "key": "Ceph",
      "scope": "tags",
      "path": "/tag/Ceph/",
      "pageKeys": [
        "v-5acd688a"
      ]
    },
    "EasyExcel": {
      "key": "EasyExcel",
      "scope": "tags",
      "path": "/tag/EasyExcel/",
      "pageKeys": [
        "v-41e2b063"
      ]
    },
    "OnlyOffice": {
      "key": "OnlyOffice",
      "scope": "tags",
      "path": "/tag/OnlyOffice/",
      "pageKeys": [
        "v-165bc73b"
      ]
    },
    "Poi": {
      "key": "Poi",
      "scope": "tags",
      "path": "/tag/Poi/",
      "pageKeys": [
        "v-091f4df9"
      ]
    },
    "WebService": {
      "key": "WebService",
      "scope": "tags",
      "path": "/tag/WebService/",
      "pageKeys": [
        "v-2a4b324a"
      ]
    },
    "Vue": {
      "key": "Vue",
      "scope": "tags",
      "path": "/tag/Vue/",
      "pageKeys": [
        "v-4e38efb3",
        "v-4fda8722",
        "v-790c0355"
      ]
    },
    "VuePress": {
      "key": "VuePress",
      "scope": "tags",
      "path": "/tag/VuePress/",
      "pageKeys": [
        "v-6ffbb6db",
        "v-5b9558ca",
        "v-921ea9ca"
      ]
    },
    "LLM": {
      "key": "LLM",
      "scope": "tags",
      "path": "/tag/LLM/",
      "pageKeys": [
        "v-9e33fd64",
        "v-36e6c066"
      ]
    },
    "CentOS": {
      "key": "CentOS",
      "scope": "tags",
      "path": "/tag/CentOS/",
      "pageKeys": [
        "v-75cbd388"
      ]
    },
    "Git": {
      "key": "Git",
      "scope": "tags",
      "path": "/tag/Git/",
      "pageKeys": [
        "v-24218ec4"
      ]
    }
  },
  "categories": {
    "后端": {
      "key": "后端",
      "scope": "categories",
      "path": "/categories/后端/",
      "pageKeys": [
        "v-f6dcfe16",
        "v-65a62e07",
        "v-15ca2d81",
        "v-1227ff87",
        "v-5acd688a",
        "v-41e2b063",
        "v-165bc73b",
        "v-091f4df9",
        "v-2a4b324a",
        "v-2ab2a5ca"
      ]
    },
    "前端": {
      "key": "前端",
      "scope": "categories",
      "path": "/categories/前端/",
      "pageKeys": [
        "v-4e38efb3",
        "v-4fda8722",
        "v-6ffbb6db",
        "v-5b9558ca",
        "v-790c0355",
        "v-921ea9ca"
      ]
    },
    "人工智能": {
      "key": "人工智能",
      "scope": "categories",
      "path": "/categories/人工智能/",
      "pageKeys": [
        "v-9e33fd64",
        "v-36e6c066"
      ]
    },
    "工具": {
      "key": "工具",
      "scope": "categories",
      "path": "/categories/工具/",
      "pageKeys": [
        "v-75cbd388",
        "v-24218ec4"
      ]
    }
  },
  "timeline": {}
}