/**
 * Generated by "@vuepress/plugin-blog"
 */
export default {
  "tags": {
    "Micorservice": {
      "key": "Micorservice",
      "scope": "tags",
      "path": "/tag/Micorservice/",
      "pageKeys": [
        "v-1227ff87"
      ]
    },
    "Docker": {
      "key": "Docker",
      "scope": "tags",
      "path": "/tag/Docker/",
      "pageKeys": [
        "v-65a62e07",
        "v-f6dcfe16"
      ]
    },
    "Ceph": {
      "key": "Ceph",
      "scope": "tags",
      "path": "/tag/Ceph/",
      "pageKeys": [
        "v-5acd688a"
      ]
    },
    "MySQL": {
      "key": "MySQL",
      "scope": "tags",
      "path": "/tag/MySQL/",
      "pageKeys": [
        "v-022ff53e",
        "v-15ca2d81",
        "v-2ab2a5ca"
      ]
    },
    "WebService": {
      "key": "WebService",
      "scope": "tags",
      "path": "/tag/WebService/",
      "pageKeys": [
        "v-2a4b324a"
      ]
    },
    "Poi": {
      "key": "Poi",
      "scope": "tags",
      "path": "/tag/Poi/",
      "pageKeys": [
        "v-091f4df9"
      ]
    },
    "OnlyOffice": {
      "key": "OnlyOffice",
      "scope": "tags",
      "path": "/tag/OnlyOffice/",
      "pageKeys": [
        "v-165bc73b"
      ]
    },
    "VuePress": {
      "key": "VuePress",
      "scope": "tags",
      "path": "/tag/VuePress/",
      "pageKeys": [
        "v-5b9558ca",
        "v-6ffbb6db",
        "v-921ea9ca"
      ]
    },
    "Git": {
      "key": "Git",
      "scope": "tags",
      "path": "/tag/Git/",
      "pageKeys": [
        "v-24218ec4"
      ]
    }
  },
  "categories": {
    "后端": {
      "key": "后端",
      "scope": "categories",
      "path": "/categories/后端/",
      "pageKeys": [
        "v-1227ff87",
        "v-65a62e07",
        "v-5acd688a",
        "v-f6dcfe16",
        "v-022ff53e",
        "v-2a4b324a",
        "v-091f4df9",
        "v-15ca2d81",
        "v-2ab2a5ca",
        "v-165bc73b"
      ]
    },
    "前端": {
      "key": "前端",
      "scope": "categories",
      "path": "/categories/前端/",
      "pageKeys": [
        "v-5b9558ca",
        "v-6ffbb6db",
        "v-921ea9ca"
      ]
    },
    "工具": {
      "key": "工具",
      "scope": "categories",
      "path": "/categories/工具/",
      "pageKeys": [
        "v-24218ec4"
      ]
    }
  },
  "timeline": {}
}