/**
 * Generated by "@vuepress/plugin-blog"
 */
export default {
  "tags": {
    "道": {
      "key": "道",
      "scope": "tags",
      "path": "/tag/道/",
      "pageKeys": [
        "v-2d92859e",
        "v-3ec94b9a",
        "v-06af9d94",
        "v-cbbc8128"
      ]
    },
    "Docker": {
      "key": "Docker",
      "scope": "tags",
      "path": "/tag/Docker/",
      "pageKeys": [
        "v-d8bc6e10",
        "v-539ebe6c"
      ]
    }
  },
  "categories": {
    "传统文化": {
      "key": "传统文化",
      "scope": "categories",
      "path": "/categories/传统文化/",
      "pageKeys": [
        "v-2d92859e",
        "v-3ec94b9a",
        "v-06af9d94",
        "v-cbbc8128"
      ]
    },
    "后端": {
      "key": "后端",
      "scope": "categories",
      "path": "/categories/后端/",
      "pageKeys": [
        "v-d8bc6e10",
        "v-539ebe6c"
      ]
    }
  },
  "timeline": {}
}