/**
 * Generated by "@vuepress/plugin-blog"
 */

import sorters from './pageSorters'
import filters from './pageFilters'

export default [{
  pid: "tags",
  id: "Docker",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/Docker/","interval":[0,2]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "tags",
  id: "工作",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/工作/","interval":[0,3]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "tags",
  id: "微服务",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/微服务/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "tags",
  id: "MySQL",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/MySQL/","interval":[0,2]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "tags",
  id: "VuePress",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/VuePress/","interval":[0,3]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "tags",
  id: "Git",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/Git/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "categories",
  id: "后端",
  filter: filters.categories,
  sorter: sorters.categories,
  pages: [{"path":"/categories/后端/","interval":[0,8]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "categories",
  id: "前端",
  filter: filters.categories,
  sorter: sorters.categories,
  pages: [{"path":"/categories/前端/","interval":[0,3]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "categories",
  id: "工具",
  filter: filters.categories,
  sorter: sorters.categories,
  pages: [{"path":"/categories/工具/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
}]