name: Deploy GitHub Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "yarn"
          
      - name: yarn set version 
        uses: borales/actions-yarn@v4
        with:
          cmd: set version 4.6.0
      - name: yarn install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: yarn build
        uses: borales/actions-yarn@v4
        with:
          cmd: build

      # 添加 CNAME 文件到部署目录
      - name: Add CNAME
        run: |
          echo "cleaner.love" > src/.vuepress/dist/CNAME

      - name: Deploy to GH Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: src/.vuepress/dist
          clean: true
          force: true
